from enum import Enum


class CommunicationEvent(str, Enum):
    CONVERSATION = "CONVERSATION"

    MISSION_STARTED = "MISSION_STARTED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_FAILED = "MISSION_FAILED"

    TARGET_FOUND = "TARGET_FOUND"
    TARGET_LOST = "TARGET_LOST"

    STATUS = "STATUS"
    WARNING = "WARNING"
    ERROR = "ERROR"
